#!/usr/bin/python3

"""
Copyright 2014 Jonathan Vasquez <jvasquez1011@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from libs.Manager import Manager
from libs.Toolkit import Toolkit

tools = Toolkit()

class Boot(object):
	def __init__(self):
		# Print the header information
		tools.print_info()

		# Gets parameters
		tools.welcome()

		# Sets up the Manager ;) (This is what is going to write our file)
		self.manager = Manager()

		# Sets the arguments retrieved by the parameters
		self.manager.set_args(tools)

	def start(self):
		# Installs the bootloader.. or not
		if tools.install_bl_flag == 1:
			self.manager.install_bootloader()
		else:
			tools.ewarn("Skipping bootloader installation ...")

		# Create and write the bootloader configuration file
		self.manager.write_entries()

if __name__ == "__main__":
	booter = Boot()
	booter.start()
