#!/usr/bin/env python

# Copyright (C) 2014 Jonathan Vasquez <fearedbliss@funtoo.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from libs import Scanner
from libs import Manager
from libs import Toolkit

class Boot(object):
	def __init__(self):
		self.toolkit = Toolkit.Toolkit()
		self.scanner = Scanner.Scanner()
		self.manager = Manager.Manager(self.scanner, self.toolkit)

	def start(self):
		# Let's the user know that we are beginning
		self.toolkit.start_message()

		# Find all kernels in /boot/kernels
		self.manager.set_kernel_list(self.scanner.get_kernels())

		# Detect the /boot and / partitions and use them to correctly
		# add the correct modules for grub 2
		#self.scanner.scan_fstab()

		# Print the kernels found
		self.manager.print_kernels()

		# Create and write the bootloader configuration file
		self.manager.write_entries()

		# Create a symlink in /boot that points back to itself
		self.toolkit.create_bootlink()

		# Let's the user know that we are done
		self.toolkit.complete_message()

if __name__ == "__main__":
	booter = Boot()
	booter.start()
